baseURL = 'www.ashwinsundar.com/'
languageCode = 'en-us'
title = 'Ashwin Sundar'
theme = 'ashwin'
enableEmoji = 'true'
enableRobotsTXT = 'true'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
